### ISSUE TITLE
Create Python test that captures image of an application during x time interval

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/HypeVision#1]
I am trying to start using TDD, so instead of writing the app logic straight away lets create a test that will capture an image of any application every 5 - 10 seconds (maybe less?)

Possible solution: https://github.com/asweigart/pyautogui

**Comment by adilanchian** [comment]
Since we are currently starting this build on Mac, there is no point to use modules specific to Mac, such as finding a specific program window, so we will wait for this when on Windows. We can use something like win32

**Comment by adilanchian** [comment]
Got some good work done today! Essentially setup most of the Python env except some VSCode issues. Will handle that. Getting the first unit test created. Essentially just trying to take screenshots ever second and saving to folder and list. Test will pass when we have x amount of screenshots in list.

**Comment by adilanchian96** [comment]
For capturing an app window, heres a possible solution (takes a screenshot):
https://stackoverflow.com/questions/69645/take-a-screenshot-via-a-python-script-linux/16141058#16141058

**Comment by adilanchian** [comment]
Thanks for this, @adilanchian96 ! I actually have some code that will be pushed up for this issue. I think it will be a great approach for it.
